#!/bin/bash

export PATH=/home/pmoosi/Documents/KTH/2023-ss/thesis/the-tool/pipeline/node-wrapper:$PATH

python3.8 /home/pmoosi/Documents/KTH/2023-ss/thesis/the-tool/pipeline/node-wrapper/node.py "$@"
