#!/bin/bash

NODE_WRAPPER="$THE_TOOL_HOME"/pipeline/node-wrapper

if [[ ":$PATH:" != *":$NODE_WRAPPER:"* ]]; then
  # If the directory is not in the path, add it
  export PATH="$NODE_WRAPPER:$PATH"
fi

# echo "RUN NPM!!!"
# echo "$NVM_DIR"/versions/node/v18.12.1/bin/npm
# echo $NODE_WRAPPER
# echo $PATH

"$NVM_DIR"/versions/node/v18.12.1/bin/npm "$@"
#$GRAAL_NPM_HOME "$@"