#!/bin/bash

CUR_DIR=$(pwd)
# cd bash dir to get dirname
NODE_WRAPPER=$(cd -- $(dirname $0) >/dev/null 2>&1; pwd)
# cd back
cd $CUR_DIR

if [[ ":$PATH:" != *":$NODE_WRAPPER:"* ]]; then
  # If the directory is not in the path, add it
  export PATH="$NODE_WRAPPER:$PATH"
fi

# echo "RUN NPM!!!"
# echo "$NVM_DIR"/versions/node/v18.12.1/bin/npm
# echo $NODE_WRAPPER
# echo $PATH

"$NVM_DIR"/versions/node/v18.12.1/bin/npm "$@"
#$GRAAL_NPM_HOME "$@"